---
openapi: 3.0.0
info:
  title: Abler API
  description: |
    This is the description of the Abler API
  version: 1.0.0
servers:
- url: https://empresa.abler.com.br/api/public/v1
paths:
  /candidates:
    get:
      tags:
      - candidates
      summary: Returns a collection of the candidates
      description: Returns a collection of the candidates
      security:
        - Bearer: []
      parameters:
        - in: query
          name: name
          description: Filtrar os candidatos pelo nome
          schema:
            type: string
        - in: query
          name: email
          description: Filtrar os candidatos pelo e-mail
          schema:
            type: string
      responses:
        "200":
          description: Successful Operation
          headers:
            Authorization:
              schema:
                type: string
              description: "Bearer JWT"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candidate'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /customers:
    get:
      tags:
      - customers
      summary: Returns a collection of the customers
      description: Returns a collection of the customers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /vacancy:
    get:
      tags:
      - vacancies
      summary: Returns a collection of your vacancies
      description: Returns a collection of your vacancies
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vacancy'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Candidate:
      type: object
      properties:
        name:
          type: string
          description: Nome do candidato
          example: Nome
        email:
          type: string
          description: E-mail do candidato
          example: email@gmail.com
        phone:
          type: integer
          description: Telefone do candidato
          example: 41988889999
    Customer:
      type: object
      properties:
        corporate_name:
          type: string
        trading_name:
          type: string
        cnpj:
          type: integer
          example: 42434481000193
        active:
          type: boolean
        additional_info:
          type: string
    Vacancy:
      type: object
      properties:
        title:
          type: string
        salary:
          type: integer
          example: 2500.0
        educational_level:
          type: string
          enum:
            - ensino_fundamental
            - ensino_medio
            - ensino_medio_tecnico
            - tecnico
            - graduacao
            - pos
            - mba
            - mestrado
            - doutorado
        contracting_regime:
          type: string
          enum:
            - avaliacao_psicologica
            - clt
            - pj
            - contrato_hibrido
            - estagiario
            - freelancer
            - intermitente
            - periodo_determinado
            - profissional_independente_contrato_societario
            - staff
            - temporario
            - terceiro
            - aprendiz
        available_for_travel:
          type: boolean
        available_for_change:
          type: boolean
        available_for_homeoffice:
          type: boolean
        working_journey:
          type: string
        quantity:
          type: integer
        educational_level_status:
          type: string
          enum:
            - cursando
            - completo
            - indiferente
        slug:
          type: string
        required_experience:
          type: boolean
        status:
          type: string
          enum:
            - draft
            - waiting_approval
            - ready_for_publish
            - published
            - stopped
            - forwarded_by_customer
            - finished
            - canceled
            - customer_request
        released:
          type: boolean
        requisition_type:
          type: string
          enum:
            - administracao_contrato
            - alocacao
            - banco_talentos
            - expansao
            - hunting
            - reposicao
            - substituicao
        notify_feedback:
          type: boolean
        notify_invitation:
          type: boolean
        description:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    ApiResponse:
      type: object
      properties:
        status:
          type: string
        status_code:
          type: integer
        title:
          type: string
        detail:
          type: string
        fields:
          type: object
